FROM debian:bullseye

RUN apt-get update

# RUN apt-get update && \
#     apt-get -y install apt-transport-https lsb-release ca-certificates curl

# Install PHP 7.4 and composer (php-curl makes composer faster)
# RUN curl -sSLo /usr/share/keyrings/deb.sury.org-php.gpg https://packages.sury.org/php/apt.gpg && \
#     echo "deb [signed-by=/usr/share/keyrings/deb.sury.org-php.gpg] https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/php.list && \
#     apt-get update
#     apt-get install php7.4-cli composer
RUN apt-get install -y composer php-curl

# Install node and yarn
RUN apt-get install -y yarnpkg

RUN apt-get install zip

ARG DATA_CHOWN=1000
COPY --chown=$DATA_CHOWN . /data
WORKDIR /data
USER $DATA_CHOWN

ENTRYPOINT ["bash", "scripts/build-entrypoint.sh"]
